### ISSUE TITLE
Show link to travelable in menu

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#522]
- When I'm on the wheelmap map view, I want to see a link to Wheelmap's sister project travelable so I can learn about the general accessibility of that city. 
- The link is only displayed if:
1. I'm in one of the cities with travelable information (list here: http://travelable.info/#infoseiten ) and
2. my locale is German

Example: When I'm on https://wheelmap.org/map#/?lat=52.52207036136366&lon=13.401947021484375&zoom=11 I see a link to  http://travelable.info/infoseiten/berlin/ .

Sketch:
<img width="931" alt="ohne_titel_key" src="https://cloud.githubusercontent.com/assets/218506/21588400/946d4dde-d0e6-11e6-9785-9c6acfd97d09.png">

**Comment by holgerd** [comment]
we don't like this approach.

New idea:
Add a main menu link in the German version "Reiseführer" which links to http://travelable.info/ (no dependency to the map location).

**Comment by 1000miles** [comment]
maybe rethinking the main menu concept (break points, burger icon) would be the best here because we might not have enough space soon for smaller desktop screens (13") when we need to add "faq" and "travel guide" to the current main menu in the future? also we need to consider that the translated text could be much longer in other languages.

**Comment by 1000miles** [comment]
Obviously when using `//travelable.info` as external link in the main menu it leads to following page https://travelable.info where not all stylesheets are loaded properly, so for now we will add the `http:` protocol to the link to fix this until ssl/tls is enabled on travelable.info in the future. 

![00000231](https://cloud.githubusercontent.com/assets/4077916/21675908/ea143dc0-d333-11e6-886a-2dd5932bd900.png)

**Comment by holgerd** [comment]
Since we only offer the travel guide in German for the foreseeable future, I suggest we omit the link in all other languages altogether.

Can you please change this?

Other than that, LGTM.

**Comment by Hoverbear** [comment]
@1000miles travelable.info works on https the assets it loads are just hardcoded to be over http. :( I asked on Slack and it looks like @thermann78 would be the person to talk to about resolving this.

**Comment by 1000miles** [comment]
@Hoverbear Thanks, @hoverbear. 

@thermann78 How do we progress here? Any feedback? :)

**Comment by 1000miles** [comment]
**Update, 2017-01-09:**

- deployed to staging, 2017-01-06
- deployed to production, 2017-01-09 with [release 20170109111423](https://github.com/sozialhelden/wheelmap/releases/tag/production-20170109111423) &  [release 20170109110124](https://github.com/sozialhelden/wheelmap/releases/tag/production-20170109110124)

**Comment by thermann78** [comment]
@Hoverbear @1000miles issue fixed, thx 4 report 👍

**Comment by Hoverbear** [comment]
@thermann78 I cannot confirm that the issue is fixed.


<img width="750" alt="screen shot 2017-01-09 at 12 30 20" src="https://cloud.githubusercontent.com/assets/130903/21765174/7d2813d0-d667-11e6-9d75-487cf4f53600.png">

**Comment by 1000miles** [comment]
@thermann78  me, too. i still see the same assets issue as @hoverbear mentioned. 

let's close this ticket and create a follow-up ticket for this.

**Comment by thermann78** [comment]
Sorry, server-side caching. Now srsly fixed :rofl:

**Comment by Hoverbear** [comment]
Confirmed!

**Comment by 1000miles** [comment]
Re-opening again because of opening @TODO:

- [ ]  change `http://travelable.info` back to `//travelable.info` - tbd by @1000miles
- [ ] create follow-up ticket for `https` issue on travelable.info  - tbd by @thermann78

**Comment by 1000miles** [comment]
As discussed with @schultyy and @justahero we will change to `https` protocol due to following reasons:
- loading errors (e.g. mixed content) will be discovered faster
- if ssl/tls is available on a domain we should use it

**Comment by 1000miles** [comment]
**Update, 2017-01-09:**

Deployed to production today with [release 20170110101704]( https://github.com/sozialhelden/wheelmap/releases/tag/production-20170110101704). Closing.
