### ISSUE TITLE
URL with umlaut cannot be saved on /nodes/edit

### ISSUE THREAD

**Issue by holgerd** [sozialhelden/wheelmap#69]
I'm on the node edit page (eg. http://wheelmap.org/nodes/301758347 and type a URL with umlaut in in the field "Website", eg. http://bäckerei.de ). I submit the form.

I expect that the new data is saved and I see a confirmation message.

Instead, I see an error message saying the URL is invalid.

Additional user report:
Sowohl http://www.xn--grtnerei-lenz-bfb.de/ als auch http://www.gärtnerei-lenz.de/ werden beanstandet.

**Comment by lennerd** [comment]
0b53e2334362f1fa30449f8a17f5dd9a8cfaa170 Will be fixed on next deploy.

**Comment by lennerd** [comment]
@holgerd Is fixed and on staging.

**Comment by holgerd** [comment]
@lennerd the bug is still there on staging:

![dieser_ort_ist_auf_wheelmap_org__allianz_generalvertretung_ilva_kauczor__versicherung__sonstiges](https://cloud.githubusercontent.com/assets/218506/11513914/20664548-9876-11e5-8f64-2794d7bd7507.png)

**Comment by lennerd** [comment]
@Xylakant @skade Any ideas for a good validation algorithm? If not, we should go back to simply check for having a protocoll in the beginning.
